[package]
name = "transfer-cli"
version = "0.1.0-test.5"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "p2p-transfer"
path = "src/main.rs"

[dependencies]
transfer-core = { path = "../transfer-core" }

p2p-sdk.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "time", "sync", "net", "signal"] }
quinn.workspace = true
rcgen.workspace = true
rustls.workspace = true
shell-words = "1.1"
rustyline = "15.0"
