[package]
name = "transfer-cli"
version = "0.1.0-test.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "p2p-transfer"
path = "src/main.rs"

[dependencies]
transfer-core = { path = "../transfer-core" }

p2p-sdk = { git = "https://github.com/juezhong/p2p-sdk", rev = "4111875e3c38ffc6b88fa9c7f179e07184e465ac" }
tokio = { version = "1", features = ["macros", "rt", "time", "sync", "net", "signal"] }
quinn = "0.11"
rcgen = "0.14"
rustls = "0.23"
shell-words = "1.1"
